- name: install apache2
  apt:
    name: apache2
    state: installed
    install_recommends: yes

- name: deploying apache2.conf
  template:
    src: etc/apache2/apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2

